//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <wchar.h>
#include <windows.h>

// ------------------------ Structures ------------------------

struct struct1 {
    int32_t e0;
    int32_t e1;
    int32_t e2;
    int32_t e3;
};

struct struct2 {
    int32_t e0;
    int32_t e1;
    int32_t e2;
    int32_t e3;
};

struct struct3 {
    int32_t e0;
    int32_t e1;
    int32_t e2;
    int32_t e3;
};

struct _EXCEPTION_POINTERS {
    struct _EXCEPTION_RECORD * e0;
    struct _CONTEXT * e1;
};

struct _EXCEPTION_RECORD {
    int32_t e0;
    int32_t e1;
    struct _EXCEPTION_RECORD * e2;
    int32_t * e3;
    int32_t e4;
    int32_t e5[1];
};

struct _M128A {
    int32_t e0;
    int64_t e1;
};

struct _CONTEXT {
    int32_t e0;
    int32_t e1;
    int32_t e2;
    int32_t e3;
    int32_t e4;
    int32_t e5;
    int32_t e6;
    int32_t e7;
    int16_t e8;
    int16_t e9;
    int16_t e10;
    int16_t e11;
    int16_t e12;
    int16_t e13;
    int32_t e14;
    int32_t e15;
    int32_t e16;
    int32_t e17;
    int32_t e18;
    int32_t e19;
    int32_t e20;
    int32_t e21;
    int32_t e22;
    int32_t e23;
    int32_t e24;
    int32_t e25;
    int32_t e26;
    int32_t e27;
    int32_t e28;
    int32_t e29;
    int32_t e30;
    int32_t e31;
    int32_t e32;
    int32_t e33;
    int32_t e34;
    int32_t e35;
    int32_t e36;
    int32_t e37;
    int32_t e38;
    struct _M128A e39[26];
    int32_t e40;
    int32_t e41;
    int32_t e42;
    int32_t e43;
    int32_t e44;
    int32_t e45;
};

struct _onexit_table_t {
    void (**e0)();
    void (**e1)();
    void (**e2)();
};

struct tagSAFEARRAYBOUND {
    int32_t e0;
    int32_t e1;
};

struct tagSAFEARRAY {
    int16_t e0;
    int16_t e1;
    int32_t e2;
    int32_t e3;
    int32_t * e4;
    struct tagSAFEARRAYBOUND e5[1];
};

// ------------------------- Classes --------------------------

// .?AVbad_alloc@std@@ (base classes: .?AVexception@std@@)
// .?AVbad_array_new_length@std@@ (base classes: .?AVbad_alloc@std@@, .?AVexception@std@@)
// .?AVexception@std@@
// .?AVtype_info@@
// `X

// ------------------- Function Prototypes --------------------

int32_t _3f__3f_0ios_base_40_std_40__40_IAE_40_XZ(void);
int32_t _3f__3f_1bad_typeid_40_std_40__40_UAE_40_XZ(void);
int32_t _3f__3f_1ios_base_40_std_40__40_UAE_40_XZ(void);
int32_t _3f__3f_1money_base_40_std_40__40_UAE_40_XZ(void);
void _3f__3f_3_40_YAXPAXI_40_Z(int32_t * a1, int32_t a2);
void _3f___scrt_initialize_type_info_40__40_YAXXZ(void);
void _3f___scrt_uninitialize_type_info_40__40_YAXXZ(void);
void _3f__Tidy_40__3f__24__Mpunct_40_D_40_std_40__40_AAEXXZ(void);
int32_t _3f_dllmain_dispatch_40__40_YAHQAUHINSTANCE___40__40_KQAX_40_Z(int32_t * a1, int64_t a2, int32_t * a3);
int32_t _40__guard_check_icall_40_4(void);
int32_t ___acrt_initialize(void);
int32_t ___CxxFrameHandler3(void);
int32_t ___isa_available_init(void);
int32_t ___local_stdio_printf_options(void);
int32_t ___local_stdio_scanf_options(void);
int32_t ___scrt_dllmain_after_initialize_c(void);
int32_t ___scrt_dllmain_before_initialize_c(void);
int32_t ___scrt_dllmain_crt_thread_detach(void);
int32_t ___scrt_dllmain_uninitialize_critical(void);
int32_t ___scrt_get_dyn_tls_init_callback(void);
int32_t ___scrt_is_nonwritable_in_current_image(void);
int32_t ___scrt_is_ucrt_dll_in_use(void);
int32_t ___std_exception_copy(void);
int32_t ___std_exception_destroy(void);
int32_t __callnewh(int32_t Size);
void __cexit(void);
int32_t __crt_atexit(void);
void __CxxThrowException_40_8(int32_t * pExceptionObject, int32_t * pThrowInfo);
int32_t __except_handler4_common(void);
int32_t __execute_onexit_table(struct _onexit_table_t * Table);
int32_t __initialize_onexit_table(struct _onexit_table_t * Table);
void __initterm(void (**First)(), void (**Last)());
int32_t __initterm_e(int32_t (**First)(), int32_t (**Last)());
int32_t __is_c_termination_complete(void);
int32_t __register_onexit_function(struct _onexit_table_t * Table, int32_t (*Function)());
int32_t __seh_filter_dll(int32_t ExceptionNum, struct _EXCEPTION_POINTERS * ExceptionPtr);
bool _IsProcessorFeaturePresent_40_4(int32_t ProcessorFeature);
int32_t * _malloc(int32_t size);
int32_t * _memset(int32_t * s, int32_t c, int32_t n);
int32_t DllCanUnloadNow(void);
int32_t DllGetClassObject(int32_t a1, int32_t a2, int32_t a3);
int32_t DllRegisterServer(void);
int32_t DllUnregisterServer(void);
int32_t function_10001000(void);
int32_t function_10001060(void);
int32_t function_10001070(void);
int32_t function_100010d0(void (*func)());
int32_t function_100010e0(int32_t str, int32_t str2);
int32_t function_10001120(void);
int32_t function_100011a0(int32_t a1, int32_t a2, int32_t a3);
int32_t function_100012a0(int32_t a1);
int32_t function_100012c0(int32_t * a1, int32_t a2, int32_t a3);
int32_t function_10001330(int32_t a1, int32_t a2, int32_t a3);
int32_t function_100013c0(int32_t a1);
int32_t function_100013e0(int32_t a1);
int32_t function_10001460(int32_t a1);
int32_t function_10001480(void);
int32_t function_10001490(int32_t a1);
int32_t function_10001530(void);
int32_t function_10001550(void);
int32_t function_10001580(void);
int32_t function_100015b0(int32_t a1);
int32_t function_100015f0(void);
int32_t function_10001750(int32_t a1, int32_t a2);
int32_t function_100017d0(void);
int32_t function_100017e0(void);
int32_t function_100017f0(void);
int32_t function_10001800(void);
int32_t function_10001810(int32_t a1, int32_t a2, int32_t a3);
int32_t function_10001ab0(int32_t a1, int32_t a2);
int32_t function_10001ad0(char a1);
int32_t function_10001c20(int32_t hLibModule, int32_t a2);
int32_t function_10001fe0(int32_t a1);
int32_t function_10002030(int32_t a1);
int32_t function_100020b0(int32_t a1, int32_t a2);
int32_t function_10002120(int32_t a1, int32_t a2, int32_t a3);
int32_t function_10002180(void);
int32_t function_100022a0(int32_t * a1, int32_t a2, int32_t a3);
int32_t function_100023b3(void);
int32_t function_10002513(void);
int32_t function_1000258b(void);
int32_t function_10002929(void);
int32_t function_10002936(void);
int32_t function_100030eb(void);
int32_t function_100030f0(int32_t a1);
int32_t function_100030fe(int32_t a1);
int32_t function_10003110(int32_t a1);
int32_t function_100032b0(int32_t a1);
int32_t function_100032f0(void);
int32_t function_10003320(char a1);
int32_t function_10003360(int32_t a1, int32_t a2, int32_t a3);
int32_t function_10003390(void);
int32_t function_10003396(void);
int32_t function_1000339c(void);
int32_t function_100033b4(int32_t * a1);
void function_100033e4(int32_t * ptr);
int32_t function_100033f0(void);
int32_t function_10003436(void);
int32_t function_10003484(int32_t * s1, int32_t * s2, int32_t n);
int32_t function_10003490(void);
int32_t function_100034c0(void);
int32_t function_100034f0(void);
int32_t function_10003540(int32_t * pvarg);

// --------------------- Global Variables ---------------------

int32_t g1 = 0; // 0x10004150
int32_t g2 = 0x20400; // 0x10004170
int32_t g3 = -0x2cf3e99f; // 0x10004180
int32_t g4 = 0x34a715a0; // 0x10004190
int32_t g5 = 0x2df01; // 0x100041a0
int32_t g6 = 0; // 0x100041b0
int32_t g7 = 0x10003320; // 0x10004254
int32_t g8 = 0x10001330; // 0x1000425c
int32_t g9 = 0x10001330; // 0x10004278
int32_t g10 = 0x3543619c; // 0x1000479c
int32_t g11 = 0x10001330; // 0x100047d0
int32_t g12 = 0x10001330; // 0x100047ec
int32_t g13 = -2; // 0x100050d8
int32_t g14 = -2; // 0x10005188
int32_t g15 = 0; // 0x100051c4
int32_t g16 = -0x44bf19b2; // 0x10006004
int32_t g17 = 1; // 0x10006010
int32_t g18 = 10; // 0x10006018
int32_t g19 = 1; // 0x10006040
int32_t g20 = 0; // 0x10006560
int32_t g21 = 0; // 0x10006568
int32_t g22 = 0; // 0x10006570
int32_t g23 = 0; // 0x1000657c
int32_t g24 = 0; // 0x10006580
int32_t g25 = 0; // 0x10006584
int32_t g26 = 0; // 0x10006588
int32_t g27 = 0; // 0x1000658c
int32_t g28 = 0; // 0x10006590
int32_t g29 = 0; // 0x10006594
int32_t g30 = 0; // 0x10006598
int32_t g31 = 0; // 0x1000659c
int32_t g32 = 0; // 0x100065a0
int32_t g33 = 0; // 0x100065a4
int32_t g34 = 0; // 0x100065a8
int32_t g35 = 0; // 0x100065ac
int32_t g36 = 0; // 0x100065b0
int32_t g37 = 0; // 0x100065b4
int32_t g38 = 0; // 0x100065b8
int32_t g39 = 0; // 0x100065bc
int32_t g40 = 0; // 0x100065c0
int32_t g41 = 0; // 0x100065c4
int32_t g42 = 0; // 0x100065c8
int32_t g43 = 0; // 0x100065cc
int32_t g44 = 0; // 0x100065d0
int32_t g45;

// ------- Dynamically Linked Functions Without Header --------

int32_t __CxxFrameHandler3(void);
int32_t __std_exception_copy(void);
int32_t __std_exception_destroy(void);
int32_t __std_type_info_destroy_list(int32_t * a1);
int32_t __telemetry_main_invoke_trigger(void);
int32_t __telemetry_main_return_trigger(void);
int32_t _callnewh(int32_t a1);
void _cexit(void);
int32_t _crt_atexit(void);
void _CxxThrowException(int32_t * a1, int32_t * a2);
int32_t _except_handler4_common(void);
int32_t _execute_onexit_table(struct _onexit_table_t * a1);
int32_t _initialize_narrow_environment(void);
int32_t _initialize_onexit_table(struct _onexit_table_t * a1);
void _initterm(void (**a1)(), void (**a2)());
int32_t _initterm_e(int32_t (**a1)(), int32_t (**a2)());
int32_t _purecall(void);
int32_t _register_onexit_function(struct _onexit_table_t * a1, int32_t (*a2)());
int32_t _seh_filter_dll(int32_t a1, struct _EXCEPTION_POINTERS * a2);
int64_t _time64(int64_t * a1);
void InitializeSListHead(int32_t * a1);

// ------------------------ Functions -------------------------

// Address range: 0x10001000 - 0x1000105f
int32_t function_10001000(void) {
    // 0x10001000
    g28 = 0;
    g29 = 0;
    g30 = 192;
    g31 = 0x46000000;
    g32 = 1;
    g33 = 0;
    g34 = 192;
    g35 = 0x46000000;
    return 192;
}

// Address range: 0x10001060 - 0x1000106f
int32_t function_10001060(void) {
    // 0x10001060
    return _3f__3f_0_3f__24_basic_ios_40_DU_3f__24_char_traits_40_D_40_std_40__40__40_std_40__40_IAE_40_XZ();
}

// Address range: 0x10001070 - 0x100010cf
int32_t function_10001070(void) {
    // 0x10001070
    g36 = 0;
    g37 = 0;
    g38 = 192;
    g39 = 0x46000000;
    g40 = -0x3b7fe5d;
    g41 = 0x11cf2ba9;
    g42 = -0x55ffd65e;
    g43 = 0x52733d00;
    return -0x55ffd65e;
}

// Address range: 0x100010d0 - 0x100010dc
int32_t function_100010d0(void (*func)()) {
    // 0x100010d0
    return _atexit((void (*)())0x10003540);
}

// Address range: 0x100010e0 - 0x10001118
int32_t function_100010e0(int32_t str, int32_t str2) {
    // 0x100010e0
    return memcmp((int32_t *)str, (int32_t *)str2, 16) == 0;
}

// Address range: 0x10001120 - 0x10001146
int32_t function_10001120(void) {
    // 0x10001120
    int32_t result; // 0x10001120
    function_100012c0(&g28, 2, result);
    *(int32_t *)result = (int32_t)&g8;
    return result;
}

// Address range: 0x100011a0 - 0x1000129f
int32_t function_100011a0(int32_t a1, int32_t a2, int32_t a3) {
    int32_t v1 = __readfsdword(0); // bp-16, 0x100011b0
    __writefsdword(0, (int32_t)&v1);
    if (a1 != 0) {
        // 0x1000128e
        __writefsdword(0, v1);
        return -0x7ffbfef0;
    }
    int32_t * lp = (int32_t *)a3; // 0x100011db
    if (IsBadWritePtr(lp, 4)) {
        // 0x1000128e
        __writefsdword(0, v1);
        return -0x7fffbffd;
    }
    // 0x100011ef
    *lp = 0;
    _3f__3f_2_40_YAPAXI_40_Z(28);
    int32_t v2 = function_10001fe0(0); // 0x1000120f
    int32_t result = -0x7ff8fff2; // 0x10001237
    if (v2 != 0) {
        // 0x10001240
        result = *(int32_t *)*(int32_t *)v2;
    }
    // 0x1000128e
    __writefsdword(0, v1);
    return result;
}

// Address range: 0x100012a0 - 0x100012bf
int32_t function_100012a0(int32_t a1) {
    // 0x100012a0
    g25 += (a1 == 0 ? -1 : 1);
    return 0;
}

// Address range: 0x100012c0 - 0x10001304
int32_t function_100012c0(int32_t * a1, int32_t a2, int32_t a3) {
    // 0x100012c0
    int32_t result; // 0x100012c0
    function_10001460(result);
    *(int32_t *)result = (int32_t)&g9;
    *(int32_t *)(result + 4) = 0;
    g25++;
    *(int32_t *)(result + 8) = (int32_t)a1;
    *(int32_t *)(result + 12) = a2;
    return result;
}

// Address range: 0x10001310 - 0x1000132b
// Demangled:     public: virtual __thiscall std::ios_base::~ios_base(void)
int32_t _3f__3f_1ios_base_40_std_40__40_UAE_40_XZ(void) {
    // 0x10001310
    int32_t result; // 0x10001310
    *(int32_t *)result = (int32_t)&g9;
    g25--;
    return result;
}

// Address range: 0x10001330 - 0x100013b5
int32_t function_10001330(int32_t a1, int32_t a2, int32_t a3) {
    int32_t v1 = a3; // bp-16, 0x10001339
    int32_t * lp = (int32_t *)a3; // 0x1000133a
    if (IsBadWritePtr(lp, 4)) {
        // 0x100013af
        return -0x7fffbffd;
    }
    // 0x1000134b
    *lp = 0;
    int32_t * v2 = (int32_t *)(a1 + 12); // 0x1000136c
    if (*v2 <= 0) {
        // 0x100013af
        return -0x7fffbffe;
    }
    int32_t v3 = &v1; // 0x10001339
    int32_t * v4 = (int32_t *)(v3 - 4);
    int32_t v5 = 0; // 0x10001360
    *v4 = *(int32_t *)(a1 + 8) + 16 * v5;
    *(int32_t *)(v3 - 8) = a2;
    while (function_100010e0(v5, (int32_t)&g45) == 0) {
        // 0x10001366
        v5++;
        if (v5 >= *v2) {
            // 0x100013af
            return -0x7fffbffe;
        }
        *v4 = *(int32_t *)(a1 + 8) + 16 * v5;
        *(int32_t *)(v3 - 8) = a2;
    }
    // 0x1000138e
    *lp = a1;
    *v4 = a1;
    // 0x100013af
    return 0;
}

// Address range: 0x100013c0 - 0x100013d9
int32_t function_100013c0(int32_t a1) {
    int32_t * v1 = (int32_t *)(a1 + 4); // 0x100013ce
    int32_t result = *v1 + 1; // 0x100013ce
    *v1 = result;
    return result;
}

// Address range: 0x100013e0 - 0x1000142f
int32_t function_100013e0(int32_t a1) {
    int32_t * v1 = (int32_t *)(a1 + 4); // 0x100013ef
    int32_t result = *v1 - 1; // 0x100013ef
    *v1 = result;
    return result;
}

// Address range: 0x10001460 - 0x10001476
int32_t function_10001460(int32_t a1) {
    // 0x10001460
    function_10001480();
    int32_t result; // 0x10001460
    return result;
}

// Address range: 0x10001480 - 0x1000148e
int32_t function_10001480(void) {
    // 0x10001480
    int32_t result; // 0x10001480
    return result;
}

// Address range: 0x10001490 - 0x10001525
int32_t function_10001490(int32_t a1) {
    int32_t v1 = __readfsdword(0); // bp-16, 0x100014a0
    int32_t v2; // bp-4, 0x10001490
    int32_t v3 = g16 ^ (int32_t)&v2; // bp-36, 0x100014ab
    __writefsdword(0, (int32_t)&v1);
    int32_t v4 = 12; // bp-40, 0x100014b8
    int32_t v5 = _3f__3f__U_40_YAPAXI_40_Z(12); // 0x100014ba
    int32_t * v6 = &v3; // 0x100014d0
    int32_t v7 = 0; // 0x100014d0
    if (v5 != 0) {
        // 0x100014d2
        v4 = a1;
        v7 = function_100015b0(a1);
        v6 = &v4;
    }
    // 0x100014ea
    int32_t result; // 0x10001490
    *(int32_t *)result = v7;
    if (result != 0) {
        // 0x10001511
        __writefsdword(0, v1);
        return result;
    }
    // 0x10001507
    *(int32_t *)((int32_t)v6 - 4) = -0x7ff8fff2;
    function_100030f0(v7);
    // UNREACHABLE
}

// Address range: 0x10001530 - 0x10001543
int32_t function_10001530(void) {
    // 0x10001530
    return function_10001580();
}

// Address range: 0x10001550 - 0x10001580
int32_t function_10001550(void) {
    int32_t result = 0; // 0x1000155f
    int32_t v1; // 0x10001550
    if (v1 != 0) {
        // 0x10001561
        result = *(int32_t *)function_10001480();
    }
    // 0x10001579
    return result;
}

// Address range: 0x10001580 - 0x100015a6
int32_t function_10001580(void) {
    int32_t result = 0; // 0x1000158d
    int32_t v1; // 0x10001580
    if (v1 != 0) {
        // 0x1000158f
        result = function_100015f0();
        *(int32_t *)v1 = 0;
    }
    // 0x100015a2
    return result;
}

// Address range: 0x100015b0 - 0x100015e2
int32_t function_100015b0(int32_t a1) {
    // 0x100015b0
    int32_t result; // 0x100015b0
    *(int32_t *)(result + 4) = 0;
    *(int32_t *)(result + 8) = 1;
    *(int32_t *)result = function_10003110(a1);
    return result;
}

// Address range: 0x100015f0 - 0x1000163b
int32_t function_100015f0(void) {
    // 0x100015f0
    int32_t v1; // 0x100015f0
    int32_t * v2 = (int32_t *)(v1 + 8); // 0x10001602
    int32_t result = *v2 - 1; // 0x10001602
    *v2 = result;
    if (v1 != 0 && result == 0) {
        // 0x1000161e
        _3f__3f__G__non_rtti_object_40_std_40__40_UAEPAXI_40_Z(v1);
    }
    // 0x10001634
    return result;
}

// Address range: 0x100016b0 - 0x10001702
// Demangled:     public: virtual __thiscall std::bad_typeid::~bad_typeid(void)
int32_t _3f__3f_1bad_typeid_40_std_40__40_UAE_40_XZ(void) {
    // 0x100016b0
    int32_t v1; // bp-12, 0x100016b0
    int32_t v2 = &v1; // 0x100016bf
    int32_t v3; // 0x100016b0
    if (v3 != 0) {
        int16_t * v4 = (int16_t *)v3; // 0x100016c6
        int16_t * v5 = v4; // bp-16, 0x100016c6
        SysFreeString(v4);
        *(int32_t *)v3 = 0;
        v2 = (int32_t)&v5;
    }
    int32_t * v6 = (int32_t *)(v3 + 4); // 0x100016d9
    int32_t v7 = *v6; // 0x100016d9
    int32_t result; // 0x100016b0
    if (v7 != 0) {
        // 0x100016df
        v1 = v7;
        *(int32_t *)(v2 - 4) = v7;
        int32_t v8 = function_10002936(); // 0x100016ec
        *v6 = 0;
        result = v8;
    }
    // 0x100016fe
    return result;
}

// Address range: 0x10001730 - 0x10001746
// Demangled:     protected: __thiscall std::ios_base::ios_base(void)
int32_t _3f__3f_0ios_base_40_std_40__40_IAE_40_XZ(void) {
    // 0x10001730
    int32_t result; // 0x10001730
    function_10001460(result);
    return result;
}

// Address range: 0x10001750 - 0x100017c8
int32_t function_10001750(int32_t a1, int32_t a2) {
    int32_t * lp = (int32_t *)a2; // 0x10001759
    if (IsBadWritePtr(lp, 4)) {
        // 0x100017c4
        return -0x7fffbffd;
    }
    // 0x1000176a
    *lp = 0;
    if (function_100010e0(a1, (int32_t)&g1) == 0) {
        // 0x10001788
        if (function_100010e0(a1, (int32_t)&g2) != 0) {
            // 0x100017b9
            *lp = (int32_t)&g27;
            // 0x100017c4
            return 0;
        }
        // 0x1000179d
        if (function_100010e0(a1, (int32_t)&g4) == 0) {
            // 0x100017c4
            return -0x7fffbffe;
        }
    }
    // 0x100017b9
    *lp = (int32_t)&g27;
    // 0x100017c4
    return 0;
}

// Address range: 0x100017d0 - 0x100017dc
int32_t function_100017d0(void) {
    // 0x100017d0
    return 1;
}

// Address range: 0x100017e0 - 0x100017ec
int32_t function_100017e0(void) {
    // 0x100017e0
    return -0x7fffbfff;
}

// Address range: 0x100017f0 - 0x100017fc
int32_t function_100017f0(void) {
    // 0x100017f0
    return -0x7fffbfff;
}

// Address range: 0x10001800 - 0x1000180c
int32_t function_10001800(void) {
    // 0x10001800
    return -0x7fffbfff;
}

// Address range: 0x10001810 - 0x10001aac
int32_t function_10001810(int32_t a1, int32_t a2, int32_t a3) {
    // 0x10001810
    if (function_100010e0(a3, (int32_t)&g6) == 0) {
        // 0x10001a9c
        return _40___security_check_cookie_40_4();
    }
    // 0x10001851
    int32_t v1; // bp-4, 0x10001810
    int32_t v2 = &v1; // 0x10001811
    int32_t v3; // bp-116, 0x10001810
    int32_t v4 = &v3; // 0x1000182e
    int32_t v5 = v2 - 84;
    int32_t v6 = v4; // 0x10001861
    int32_t v7; // 0x10001810
    for (int32_t i = 0; i < 5; i++) {
        // 0x10001857
        v7 = v6;
        v6 = v7 - 4;
        *(int32_t *)v6 = 16 * i + v5;
        VariantInit((int32_t *)i);
    }
    int32_t v8 = v6; // 0x10001871
    if (a2 == 250) {
        // 0x10001877
        *(int32_t *)(v7 - 8) = 8;
        *(int32_t *)(v7 - 12) = 0;
        int32_t v9; // 0x10001810
        int32_t * v10 = (int32_t *)v9; // 0x10001886
        *(int32_t *)(v7 - 16) = *v10 + 80;
        *(int32_t *)(v7 - 20) = v5;
        VariantChangeType((int32_t *)5, &g45, (int16_t)&g45, (int16_t)&g45);
        *(int32_t *)(v7 - 24) = 3;
        *(int32_t *)(v7 - 28) = 0;
        *(int32_t *)(v7 - 32) = *v10 + 64;
        *(int32_t *)(v7 - 36) = v2 - 68;
        VariantChangeType(&g45, &g45, (int16_t)&g45, (int16_t)&g45);
        *(int32_t *)(v7 - 40) = 8;
        *(int32_t *)(v7 - 44) = 0;
        *(int32_t *)(v7 - 48) = *v10 + 48;
        *(int32_t *)(v7 - 52) = v2 - 52;
        VariantChangeType(&g45, &g45, (int16_t)&g45, (int16_t)&g45);
        *(int32_t *)(v7 - 56) = 0x2011;
        *(int32_t *)(v7 - 60) = 0;
        *(int32_t *)(v7 - 64) = *v10 + 32;
        int32_t v11 = v2 - 36; // 0x10001901
        *(int32_t *)(v7 - 68) = v11;
        VariantChangeType(&g45, &g45, (int16_t)&g45, (int16_t)&g45);
        *(int32_t *)(v7 - 72) = 8;
        *(int32_t *)(v7 - 76) = 0;
        *(int32_t *)(v7 - 80) = *v10 + 16;
        int32_t v12 = v7 - 84; // 0x1000192a
        *(int32_t *)v12 = v2 - 20;
        VariantChangeType(&g45, &g45, (int16_t)&g45, (int16_t)&g45);
        int16_t * v13 = (int16_t *)v11; // 0x10001939
        int32_t v14; // 0x10001810
        int32_t v15; // 0x10001810
        int32_t v16; // bp-108, 0x10001810
        if (*v13 == 0) {
            // 0x10001999
            v16 = 0;
            v15 = 0;
            v14 = v12;
        } else {
            // 0x10001942
            *(int32_t *)(v7 - 88) = v4;
            *(int32_t *)(v7 - 92) = 0;
            int32_t * v17 = (int32_t *)(v2 - 28); // 0x10001950
            *(int32_t *)(v7 - 96) = *v17;
            SafeArrayGetLBound((struct tagSAFEARRAY *)&g45, (int32_t)&g45, &g45);
            int32_t v18; // bp-112, 0x10001810
            *(int32_t *)(v7 - 100) = (int32_t)&v18;
            *(int32_t *)(v7 - 104) = 0;
            *(int32_t *)(v7 - 108) = *v17;
            SafeArrayGetUBound((struct tagSAFEARRAY *)&g45, (int32_t)&g45, &g45);
            int32_t v19 = v18 - v3 + 1; // 0x1000197a
            *(int32_t *)(v7 - 112) = (int32_t)&v16;
            int32_t v20 = v7 - 116; // 0x10001990
            *(int32_t *)v20 = *v17;
            SafeArrayAccessData((struct tagSAFEARRAY *)v19, (int32_t **)&g45);
            v15 = v19;
            v14 = v20;
        }
        int16_t v21 = *(int16_t *)*(int32_t *)(*v10 + 8); // 0x100019b8
        *(int32_t *)(v14 - 4) = (int32_t)(v21 != 0);
        *(int32_t *)(v14 - 8) = *(int32_t *)(v2 - 12);
        *(int32_t *)(v14 - 12) = v15;
        *(int32_t *)(v14 - 16) = v16;
        *(int32_t *)(v14 - 20) = *(int32_t *)(v2 - 44);
        *(int32_t *)(v14 - 24) = *(int32_t *)(v2 - 60);
        int32_t v22 = v14 - 28; // 0x10001a08
        *(int32_t *)v22 = *(int32_t *)(v2 - 76);
        int32_t v23 = function_10001ad0((char)(v21 != 0)) & 255;
        int32_t v24 = v22; // 0x10001a23
        if (*v13 != 0) {
            // 0x10001a25
            v24 = v14 - 32;
            *(int32_t *)v24 = *(int32_t *)(v2 - 28);
            SafeArrayUnaccessData((struct tagSAFEARRAY *)v23);
        }
        int16_t * v25 = (int16_t *)*(int32_t *)(*v10 + 8);
        if (v23 == 0) {
            // 0x10001a59
            *v25 = 0;
            v8 = v24;
        } else {
            // 0x10001a40
            *v25 = -1;
            v8 = v24;
        }
    }
    int32_t v26 = v8; // 0x10001a91
    for (int32_t i = 0; i < 5; i++) {
        // 0x10001a87
        v26 -= 4;
        *(int32_t *)v26 = 16 * i + v5;
        VariantClear((int32_t *)i);
    }
    // 0x10001a9c
    return _40___security_check_cookie_40_4();
}

// Address range: 0x10001ab0 - 0x10001ac2
int32_t function_10001ab0(int32_t a1, int32_t a2) {
    // 0x10001ab0
    return _time64((int64_t *)a1);
}

// Address range: 0x10001ad0 - 0x10001c14
int32_t function_10001ad0(char a1) {
    int32_t v1 = __readfsdword(0); // bp-16, 0x10001ae0
    __writefsdword(0, (int32_t)&v1);
    int32_t v2 = 0; // bp-48, 0x10001b25
    int32_t v3; // 0x10001ad0
    srand(function_10001ab0(0, v3));
    int32_t v4 = rand(); // 0x10001b40
    if ((int32_t)((0x100000000 * (int64_t)(v4 >> 31) | (int64_t)v4) % 3) != 0 || CoInitialize(NULL) < 0) {
        // 0x10001bf9
        __writefsdword(0, v1);
        return _40___security_check_cookie_40_4();
    }
    int32_t v5 = CoCreateInstance((int32_t)&g5, NULL, 4, &g3, (int32_t **)&v2); // 0x10001b85
    if (v5 == 0) {
        int32_t v6 = rand(); // 0x10001b94
        int32_t v7; // bp-4, 0x10001ad0
        int32_t v8 = *(int32_t *)((int32_t)&v7 - 40 + 4 * (int32_t)((0x100000000 * (int64_t)(v6 >> 31) | (int64_t)v6) % 6)); // 0x10001ba2
        function_10001490(v8);
        function_10001550();
        function_10001530();
    }
    // 0x10001bf9
    __writefsdword(0, v1);
    return _40___security_check_cookie_40_4();
}

// Address range: 0x10001c20 - 0x10001cbf
int32_t function_10001c20(int32_t hLibModule, int32_t a2) {
    if (a2 != 1) {
        // 0x10001caf
        return _40___security_check_cookie_40_4();
    }
    // 0x10001c39
    g26 = hLibModule;
    DisableThreadLibraryCalls((int32_t *)hLibModule);
    int32_t lpFilename; // bp-2056, 0x10001c20
    GetModuleFileNameW(NULL, (int16_t *)&lpFilename, 1024);
    uint32_t v1 = wcsnlen((int16_t *)&lpFilename, 1024); // 0x10001c6e
    if (v1 >= 13) {
        // 0x10001c86
        int32_t v2; // bp-4, 0x10001c20
        _wcsicmp((int16_t *)((int32_t)&v2 - 2076 + 2 * v1), L"explorer.exe");
    }
    // 0x10001caf
    return _40___security_check_cookie_40_4();
}

// Address range: 0x10001cc0 - 0x10001d96
int32_t DllGetClassObject(int32_t a1, int32_t a2, int32_t a3) {
    // 0x10001cc0
    if (function_100010e0(a1, (int32_t)&g10) == 0) {
        // 0x10001d90
        return -0x7ffbfeef;
    }
    int32_t * lp = (int32_t *)a3; // 0x10001ceb
    int32_t result = -0x7fffbffd; // 0x10001cf3
    if (!IsBadWritePtr(lp, 4)) {
        // 0x10001cff
        *lp = 0;
        _3f__3f_2_40_YAPAXI_40_Z(16);
        int32_t v1 = function_10001120(); // 0x10001d18
        result = v1 != 0 ? v1 : -0x7ff8fff2;
    }
    // 0x10001d90
    return result;
}

// Address range: 0x10001da0 - 0x10001db7
int32_t DllCanUnloadNow(void) {
    // 0x10001da0
    return g25 > 0;
}

// Address range: 0x10001dc0 - 0x10001f91
int32_t DllRegisterServer(void) {
    // 0x10001dc0
    int32_t lpFilename; // bp-2056, 0x10001dc0
    GetModuleFileNameW((int32_t *)g26, (int16_t *)&lpFilename, 1024);
    int32_t phkResult; // bp-2060, 0x10001dc0
    int32_t v1 = RegCreateKeyExW(HKEY_CLASSES_ROOT, L"CLSID\\{3543619C-D563-43f7-95EA-4DA7E1CC396A}", 0, NULL, 0, 0xf003f, NULL, (int32_t **)&phkResult, NULL); // 0x10001e0c
    if (v1 != 0) {
        // 0x10001f83
        return _40___security_check_cookie_40_4();
    }
    // 0x10001e20
    RegSetValueExW((int32_t *)phkResult, NULL, 0, 1, "C", 48);
    RegCloseKey((int32_t *)phkResult);
    int32_t v2 = RegCreateKeyExW(HKEY_CLASSES_ROOT, L"CLSID\\{3543619C-D563-43f7-95EA-4DA7E1CC396A}\\InProcServer32", 0, NULL, 0, 0xf003f, NULL, (int32_t **)&phkResult, NULL); // 0x10001e67
    if (v2 != 0) {
        // 0x10001f83
        return _40___security_check_cookie_40_4();
    }
    int16_t * v3 = (int16_t *)&lpFilename;
    int32_t v4 = (int32_t)v3 + 2; // 0x10001ea6
    while (*v3 != 0) {
        // 0x10001e96
        v3 = (int16_t *)v4;
        v4 = (int32_t)v3 + 2;
    }
    // 0x10001eb7
    RegSetValueExW((int32_t *)phkResult, NULL, 0, 1, (char *)&lpFilename, 2 - ((int32_t)&lpFilename | 2) + v4 & -2);
    RegSetValueExW((int32_t *)phkResult, L"ThreadingModel", 0, 1, "A", 20);
    RegCloseKey((int32_t *)phkResult);
    int32_t v5 = RegCreateKeyExW(HKEY_LOCAL_MACHINE, L"Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Browser Helper Objects\\{3543619C-D563-43f7-95EA-4DA7E1CC396A}", 0, NULL, 0, 0xf003f, NULL, (int32_t **)&phkResult, NULL); // 0x10001f3a
    if (v5 == 0) {
        int32_t lpData = 1; // bp-2080, 0x10001f4b
        RegSetValueExW((int32_t *)phkResult, L"NoExplorer", 0, 4, (char *)&lpData, 4);
        RegCloseKey((int32_t *)phkResult);
    }
    // 0x10001f83
    return _40___security_check_cookie_40_4();
}

// Address range: 0x10001fa0 - 0x10001fd7
int32_t DllUnregisterServer(void) {
    // 0x10001fa0
    RegDeleteKeyW((int32_t *)-0x7ffffffe, L"Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Browser Helper Objects\\{3543619C-D563-43f7-95EA-4DA7E1CC396A}");
    RegDeleteKeyW((int32_t *)-0x80000000, L"CLSID\\{3543619C-D563-43f7-95EA-4DA7E1CC396A}\\InProcServer32");
    RegDeleteKeyW((int32_t *)-0x80000000, L"CLSID\\{3543619C-D563-43f7-95EA-4DA7E1CC396A}");
    return 0;
}

// Address range: 0x10001fe0 - 0x10002024
int32_t function_10001fe0(int32_t a1) {
    // 0x10001fe0
    int32_t result; // 0x10001fe0
    function_100022a0(&g36, 2, result);
    *(int32_t *)result = (int32_t)&g12;
    *(int32_t *)(result + 24) = 0;
    *(int32_t *)(result + 16) = 0;
    *(int32_t *)(result + 20) = 0;
    return result;
}

// Address range: 0x10002030 - 0x1000205e
int32_t function_10002030(int32_t a1) {
    // 0x10002030
    _3f__3f_1_3f__24__Mpunct_40_D_40_std_40__40_MAE_40_XZ();
    int32_t result; // 0x10002030
    if ((a1 & 1) != 0) {
        // 0x10002047
        _3f__3f_3_40_YAXPAXI_40_Z((int32_t *)result, (int32_t)&g45);
    }
    // 0x10002055
    return result;
}

// Address range: 0x100020b0 - 0x1000211f
int32_t function_100020b0(int32_t a1, int32_t a2) {
    if (a2 == 0) {
        // 0x100020c8
        _3f__Tidy_40__3f__24__Mpunct_40_D_40_std_40__40_AAEXXZ();
        // 0x10002119
        return 0;
    }
    int32_t v1 = a2; // bp-12, 0x100020c2
    int32_t v2 = &v1;
    _3f__Tidy_40__3f__24__Mpunct_40_D_40_std_40__40_AAEXXZ();
    *(int32_t *)(v2 - 4) = a1 + 16;
    *(int32_t *)(v2 - 8) = (int32_t)&g3;
    int32_t v3 = *(int32_t *)a2; // 0x100020e9
    *(int32_t *)(v2 - 12) = a2;
    *(int32_t *)(v2 - 16) = a2;
    int32_t result = v3; // 0x10002108
    if (v3 >= 0) {
        // 0x1000210f
        function_10002180();
        result = 0;
    }
    // 0x10002119
    return result;
}

// Address range: 0x10002120 - 0x10002172
int32_t function_10002120(int32_t a1, int32_t a2, int32_t a3) {
    int32_t * lp = (int32_t *)a3; // 0x10002129
    if (IsBadWritePtr(lp, 4)) {
        // 0x1000216e
        return -0x7fffbffd;
    }
    // 0x1000213a
    *lp = 0;
    int32_t v1 = *(int32_t *)(a1 + 16); // 0x10002146
    int32_t result = -0x7fffbffb; // 0x1000214a
    if (v1 != 0) {
        // 0x10002153
        result = *(int32_t *)v1;
    }
    // 0x1000216e
    return result;
}

// Address range: 0x10002180 - 0x10002212
int32_t function_10002180(void) {
    // 0x10002180
    int32_t v1; // 0x10002180
    int32_t v2 = *(int32_t *)(v1 + 16); // 0x1000218c
    int32_t result; // 0x10002180
    if (v2 == 0) {
        // 0x1000220e
        return result;
    }
    int32_t v3 = *(int32_t *)v2; // 0x100021a9
    result = v3;
    if (v3 < 0) {
        // 0x1000220e
        return result;
    }
    // 0x100021bb
    if (*(int32_t *)(*(int32_t *)v1 + 16) >= 0) {
        // 0x100021ee
        result = *(int32_t *)(v1 + 20);
    }
    // 0x1000220e
    return result;
}

// Address range: 0x10002220 - 0x1000229e
// Demangled:     private: void __thiscall std::_Mpunct<char>::_Tidy(void)
void _3f__Tidy_40__3f__24__Mpunct_40_D_40_std_40__40_AAEXXZ(void) {
    // 0x10002220
    int32_t v1; // bp-8, 0x10002220
    int32_t * v2 = &v1; // 0x1000222e
    int32_t v3; // 0x10002220
    int32_t v4; // 0x10002220
    if (*(int32_t *)(v4 + 20) != 0) {
        // 0x10002230
        *(int32_t *)(v4 + 24) = 0;
        int32_t * v5 = (int32_t *)(v1 + 20); // 0x1000225e
        int32_t v6 = *v5; // bp-20, 0x10002263
        *v5 = 0;
        v3 = v1;
        v2 = &v6;
    }
    int32_t v7 = *(int32_t *)(v3 + 16); // 0x10002276
    if (v7 != 0) {
        // 0x1000227c
        *(int32_t *)((int32_t)v2 - 4) = v7;
        *(int32_t *)(v1 + 16) = 0;
    }
}

// Address range: 0x100022a0 - 0x100022e4
int32_t function_100022a0(int32_t * a1, int32_t a2, int32_t a3) {
    // 0x100022a0
    int32_t result; // 0x100022a0
    function_10001460(result);
    *(int32_t *)result = (int32_t)&g11;
    *(int32_t *)(result + 4) = 0;
    g25++;
    *(int32_t *)(result + 8) = (int32_t)a1;
    *(int32_t *)(result + 12) = a2;
    return result;
}

// Address range: 0x100022f0 - 0x1000230b
// Demangled:     public: virtual __thiscall std::money_base::~money_base(void)
int32_t _3f__3f_1money_base_40_std_40__40_UAE_40_XZ(void) {
    // 0x100022f0
    int32_t result; // 0x100022f0
    *(int32_t *)result = (int32_t)&g11;
    g25--;
    return result;
}

// Address range: 0x10002382 - 0x10002390
// Demangled:     void __cdecl operator delete(void *, unsigned int)
void _3f__3f_3_40_YAXPAXI_40_Z(int32_t * a1, int32_t a2) {
    // 0x10002382
    function_10002936();
}

// Address range: 0x100023b3 - 0x100023b8
int32_t function_100023b3(void) {
    // 0x100023b3
    return function_10002936();
}

// Address range: 0x10002513 - 0x1000251d
int32_t function_10002513(void) {
    // 0x10002513
    int32_t v1; // 0x10002513
    return ___scrt_release_startup_lock(*(int32_t *)(v1 - 29));
}

// Address range: 0x1000258b - 0x1000259a
int32_t function_1000258b(void) {
    // 0x1000258b
    ___scrt_dllmain_uninitialize_critical();
    int32_t v1; // 0x1000258b
    return ___scrt_release_startup_lock(*(int32_t *)(v1 - 28));
}

// Address range: 0x1000259a - 0x100026a3
// Demangled:     int __cdecl dllmain_dispatch(struct HINSTANCE__*const, unsigned long, void *const)
int32_t _3f_dllmain_dispatch_40__40_YAHQAUHINSTANCE___40__40_KQAX_40_Z(int32_t * a1, int64_t a2, int32_t * a3) {
    int32_t v1 = &g13; // bp-8, 0x1000259c
    __SEH_prolog4(&g13, 12);
    int32_t v2; // 0x1000259a
    int32_t * v3 = (int32_t *)(v2 - 4); // 0x100025a6
    *v3 = 0;
    int32_t v4 = *(int32_t *)(v2 + 12); // 0x100025aa
    int32_t * v5; // 0x1000259a
    int32_t * v6; // 0x1000259a
    bool v7; // 0x1000259a
    bool v8; // 0x1000259a
    int32_t v9; // 0x1000259a
    int32_t v10; // 0x1000259a
    if (v4 < 3) {
        int32_t * v11 = (int32_t *)(v2 + 16);
        int32_t v12 = *(int32_t *)(v2 + 8); // 0x100025c0
        int32_t * v13 = (int32_t *)v12; // 0x100025c4
        int64_t v14 = v4; // 0x100025c4
        int32_t v15 = _3f_dllmain_raw_40__40_YGHQAUHINSTANCE___40__40_KQAX_40_Z(v13, v14, (int32_t *)*v11); // 0x100025c4
        int32_t * v16 = (int32_t *)(v2 - 28);
        *v16 = v15;
        if (v15 == 0) {
            // 0x10002694
            *v3 = -2;
            return __SEH_epilog4();
        }
        int32_t v17 = v12; // bp-32, 0x100025da
        int32_t v18 = _3f_dllmain_crt_dispatch_40__40_YGHQAUHINSTANCE___40__40_KQAX_40_Z(v13, v14, (int32_t *)*v11); // 0x100025db
        *v16 = v18;
        if (v18 == 0) {
            // 0x10002694
            *v3 = -2;
            return __SEH_epilog4();
        }
        int32_t v19 = &v17;
        v6 = v16;
        v5 = v11;
        v7 = true;
        v8 = false;
        v10 = v19;
        v9 = v12;
        if (v4 == 1) {
            // 0x100025f2
            *(int32_t *)(v19 - 4) = v12;
            __telemetry_main_invoke_trigger();
            v6 = v16;
            v5 = v11;
            v7 = false;
            v8 = true;
            v10 = v19;
            v9 = v12;
        }
    } else {
        // 0x100025ed
        v6 = (int32_t *)(v2 - 28);
        v5 = (int32_t *)(v2 + 16);
        v7 = true;
        v8 = false;
        v10 = &v1;
        v9 = *(int32_t *)(v2 + 8);
    }
    // 0x100025f9
    *(int32_t *)(v10 - 4) = *v5;
    *(int32_t *)(v10 - 8) = v4;
    int32_t v20 = v10 - 12; // 0x100025fd
    *(int32_t *)v20 = v9;
    int32_t v21 = function_10001c20((int32_t)&g45, (int32_t)&g45); // 0x100025fe
    *v6 = v21;
    int32_t v22 = v20; // 0x1000260b
    int32_t v23; // 0x1000259a
    if (v7) {
        goto lab_0x10002638;
    } else {
        // 0x1000260d
        v22 = v20;
        if (v21 != 0) {
            goto lab_0x10002638;
        } else {
            // 0x1000262f
            *(int32_t *)(v10 - 16) = *v5;
            *(int32_t *)(v10 - 20) = v21;
            *(int32_t *)(v10 - 24) = v9;
            function_10001c20((int32_t)&g45, (int32_t)&g45);
            *(int32_t *)(v10 - 28) = *v5;
            *(int32_t *)(v10 - 32) = v21;
            *(int32_t *)(v10 - 36) = v9;
            _3f_dllmain_crt_dispatch_40__40_YGHQAUHINSTANCE___40__40_KQAX_40_Z(&g45, (int64_t)&g45, &g45);
            *(int32_t *)(v10 - 40) = *v5;
            *(int32_t *)(v10 - 44) = v21;
            int32_t v24 = v10 - 48; // 0x10002629
            *(int32_t *)v24 = v9;
            _3f_dllmain_raw_40__40_YGHQAUHINSTANCE___40__40_KQAX_40_Z(&g45, (int64_t)&g45, &g45);
            v22 = v24;
            v23 = v24;
            if (v8 == v21 == 0) {
                goto lab_0x1000263c;
            } else {
                goto lab_0x10002638;
            }
        }
    }
  lab_0x10002638:
    // 0x10002638
    v23 = v22;
    int32_t v25 = v22; // 0x1000263a
    if (v4 != 0) {
        goto lab_0x10002647;
    } else {
        goto lab_0x1000263c;
    }
  lab_0x10002647:
    if (v4 != 3) {
        // 0x10002694
        *v3 = -2;
        return __SEH_epilog4();
    }
    int32_t * v26 = (int32_t *)(v25 - 4); // 0x1000259a
    int32_t v27 = v25; // 0x1000259a
    goto lab_0x1000264c;
  lab_0x1000263c:;
    int32_t * v30 = (int32_t *)(v23 - 4);
    *v30 = v9;
    __telemetry_main_return_trigger();
    v25 = v23;
    v26 = v30;
    v27 = v23;
    if (v4 == 0) {
        goto lab_0x1000264c;
    } else {
        goto lab_0x10002647;
    }
  lab_0x1000264c:
    // 0x1000264c
    *v26 = *v5;
    *(int32_t *)(v27 - 8) = v4;
    *(int32_t *)(v27 - 12) = v9;
    int32_t v28 = _3f_dllmain_crt_dispatch_40__40_YGHQAUHINSTANCE___40__40_KQAX_40_Z(&g45, (int64_t)&g45, &g45); // 0x10002651
    *v6 = v28;
    if (v28 != 0) {
        // 0x1000265f
        *(int32_t *)(v27 - 16) = *v5;
        *(int32_t *)(v27 - 20) = v4;
        *(int32_t *)(v27 - 24) = v9;
        int32_t v29 = _3f_dllmain_raw_40__40_YGHQAUHINSTANCE___40__40_KQAX_40_Z(&g45, (int64_t)&g45, &g45); // 0x10002664
        *v6 = v29;
    }
    // 0x10002694
    *v3 = -2;
    return __SEH_epilog4();
}

// Address range: 0x10002929 - 0x10002936
// From class:    .?AVbad_alloc@std@@
// Type:          virtual member function
int32_t function_10002929(void) {
    // 0x10002929
    int32_t v1; // 0x10002929
    int32_t v2 = *(int32_t *)(v1 + 4); // 0x10002929
    return v2 != 0 ? v2 : (int32_t)"Unknown exception";
}

// Address range: 0x10002936 - 0x1000293b
int32_t function_10002936(void) {
    // 0x10002936
    free(&g45);
    return &g45;
}

// Address range: 0x100029b4 - 0x100029cc
int32_t ___scrt_dllmain_after_initialize_c(void) {
    // 0x100029b4
    int32_t v1; // 0x100029b4
    if (___scrt_is_ucrt_dll_in_use() == 0) {
        // 0x100029c4
        v1 = _initialize_narrow_environment();
    } else {
        // 0x100029bd
        v1 = ___isa_available_init();
    }
    // 0x100029c9
    return v1 & -256 | 1;
}

// Address range: 0x100029cc - 0x100029da
int32_t ___scrt_dllmain_before_initialize_c(void) {
    int32_t v1 = ___scrt_initialize_onexit_tables(0); // 0x100029ce
    return v1 & -256 | (int32_t)((char)v1 != 0);
}

// Address range: 0x100029f9 - 0x10002a06
int32_t ___scrt_dllmain_crt_thread_detach(void) {
    // 0x100029f9
    ___acrt_initialize();
    return ___acrt_initialize() & -256 | 1;
}

// Address range: 0x10002a5c - 0x10002a69
int32_t ___scrt_dllmain_uninitialize_critical(void) {
    // 0x10002a5c
    ___acrt_initialize();
    return ___acrt_initialize();
}

// Address range: 0x10002b39 - 0x10002bc6
int32_t ___scrt_is_nonwritable_in_current_image(void) {
    // 0x10002b39
    __SEH_prolog4(&g14, 8);
    int32_t v1; // 0x10002b39
    int32_t * v2 = (int32_t *)(v1 - 4); // 0x10002b45
    *v2 = 0;
    if (*(int16_t *)0x10000000 != 0x5a4d) {
        // 0x10002bc0
        *v2 = -2;
        return __SEH_epilog4();
    }
    int32_t v3 = *(int32_t *)0x1000003c; // 0x10002b57
    if (*(int32_t *)(v3 + 0x10000000) != 0x4550) {
        // 0x10002bc0
        *v2 = -2;
        return __SEH_epilog4();
    }
    // 0x10002b68
    if (*(int16_t *)(v3 + 0x10000018) == 267) {
        int32_t v4 = *(int32_t *)(v1 + 8); // 0x10002b76
        _3f_find_pe_section_40__40_YAPAU_IMAGE_SECTION_HEADER_40__40_QAEI_40_Z((char *)0x10000000, v4 - 0x10000000);
    }
    // 0x10002bc0
    *v2 = -2;
    return __SEH_epilog4();
}

// Address range: 0x10002cf7 - 0x10002d03
// Demangled:     void __cdecl __scrt_initialize_type_info(void)
void _3f___scrt_initialize_type_info_40__40_YAXXZ(void) {
    // 0x10002cf7
    InitializeSListHead(&g20);
}

// Address range: 0x10002d03 - 0x10002d0f
// Demangled:     void __cdecl __scrt_uninitialize_type_info(void)
void _3f___scrt_uninitialize_type_info_40__40_YAXXZ(void) {
    // 0x10002d03
    __std_type_info_destroy_list(&g20);
}

// Address range: 0x10002d0f - 0x10002d15
int32_t ___local_stdio_printf_options(void) {
    // 0x10002d0f
    return &g21;
}

// Address range: 0x10002d15 - 0x10002d1b
int32_t ___local_stdio_scanf_options(void) {
    // 0x10002d15
    return &g22;
}

// Address range: 0x10002d38 - 0x10002d3e
int32_t ___scrt_get_dyn_tls_init_callback(void) {
    // 0x10002d38
    return &g44;
}

// Address range: 0x10002eaf - 0x10002eb5
int32_t _40__guard_check_icall_40_4(void) {
    // 0x10002eaf
    return function_100030eb();
}

// Address range: 0x10002f3e - 0x100030df
int32_t ___isa_available_init(void) {
    struct struct2 v1; // 0x10002f7f
    struct struct1 v2; // 0x10002fc0
    // 0x10002f3e
    g23 = 0;
    g17 |= 1;
    if (!IsProcessorFeaturePresent(10)) {
        // 0x100030d8
        return 0;
    }
    // 0x10002f64
    g17 |= 2;
    g23 = 1;
    v1 = __asm_cpuid(0);
    v2 = __asm_cpuid_5(1);
    int32_t v3; // 0x10002f3e
    if ((v1.e3 ^ 0x49656e69 || v1.e2 ^ 0x6c65746e || v1.e1 ^ 0x756e6547) != 0) {
        // 0x10003015
        v3 = g24;
        goto lab_0x1000301b;
    } else {
        int32_t v4 = v2.e0 & 0xfff3ff0; // 0x10002fd5
        switch (v4) {
            case 0x30660: {
                goto lab_0x10003004;
            }
            case 0x30650: {
                goto lab_0x10003004;
            }
            case 0x20670: {
                goto lab_0x10003004;
            }
            case 0x20660: {
                goto lab_0x10003004;
            }
            case 0x106c0: {
                goto lab_0x10003004;
            }
            default: {
                if (v4 != 0x30670) {
                    // 0x10003015
                    v3 = g24;
                    goto lab_0x1000301b;
                } else {
                    goto lab_0x10003004;
                }
            }
        }
    }
  lab_0x1000301b:
    if (v1.e0 >= 7) {
        // 0x10003030
        if ((__asm_cpuid_6(7).e1 & 512) != 0) {
            // 0x10003059
            g24 = v3 | 2;
        }
    }
    int32_t v5 = v2.e2; // 0x10002fc0
    if ((v5 & 0x100000) == 0) {
        // 0x100030d8
        return 0;
    }
    // 0x1000306b
    g17 |= 4;
    g23 = 2;
    if ((v5 & 0x18000000) == 0x18000000) {
        // 0x1000308a
        __asm_xgetbv(0);
    }
    // 0x100030d8
    return 0;
  lab_0x10003004:;
    int32_t v6 = g24 | 1; // 0x1000300a
    g24 = v6;
    v3 = v6;
    goto lab_0x1000301b;
}

// Address range: 0x100030df - 0x100030eb
int32_t ___scrt_is_ucrt_dll_in_use(void) {
    // 0x100030df
    return g19 != 0;
}

// Address range: 0x100030eb - 0x100030ec
int32_t function_100030eb(void) {
    // 0x100030eb
    int32_t result; // 0x100030eb
    return result;
}

// Address range: 0x100030f0 - 0x100030fe
int32_t function_100030f0(int32_t a1) {
    // 0x100030f0
    int32_t v1; // 0x100030f0
    function_10003360(a1, 0, v1);
    // UNREACHABLE
}

// Address range: 0x100030fe - 0x10003102
int32_t function_100030fe(int32_t a1) {
    // 0x100030fe
    int32_t result; // 0x100030fe
    return result;
}

// Address range: 0x10003110 - 0x100032a1
int32_t function_10003110(int32_t a1) {
    int32_t v1 = __readfsdword(0); // bp-20, 0x10003125
    __writefsdword(0, (int32_t)&v1);
    int32_t v2 = a1; // 0x1000314b
    if (a1 == 0) {
        // 0x10003280
        __writefsdword(0, v1);
        return _40___security_check_cookie_40_4();
    }
    while (*(char *)v2 != 0) {
        // 0x10003160
        v2++;
    }
    uint32_t cbMultiByte = v2 - a1 + 1; // 0x10003169
    if (cbMultiByte <= 0xffffffff) {
        // 0x10003176
        function_100030f0(-0x7ff8ffa9);
        // UNREACHABLE
    }
    int32_t v3 = 0; // bp-84, 0x10003188
    char * lpMultiByteStr = (char *)a1; // 0x1000318a
    uint32_t cchWideChar = MultiByteToWideChar(0, 0, lpMultiByteStr, cbMultiByte, NULL, 0); // 0x1000318a
    if (cchWideChar == 0) {
        int32_t errorCode = GetLastError(); // 0x10003199
        function_100030f0(errorCode < 1 ? errorCode : errorCode & 0xffff | -0x7ff90000);
        // UNREACHABLE
    }
    int32_t * lpWideCharStr; // 0x10003110
    if (cchWideChar > 4095) {
        int32_t * mem = malloc(2 * cchWideChar); // 0x100031da
        lpWideCharStr = mem;
        if (mem == NULL) {
            // 0x1000320f
            function_100030f0(-0x7ff8fff2);
            // UNREACHABLE
        }
    } else {
        // 0x1000320b
        __alloca_probe_16(cchWideChar);
        lpWideCharStr = &v3;
    }
    // 0x10003219
    if (MultiByteToWideChar(0, 0, lpMultiByteStr, cbMultiByte, (int16_t *)lpWideCharStr, cchWideChar) == 0) {
        if (cchWideChar >= 0x1000) {
            // 0x10003235
            free(lpWideCharStr);
        }
        int32_t errorCode2 = GetLastError(); // 0x1000323e
        function_100030f0(errorCode2 < 1 ? errorCode2 : errorCode2 & 0xffff | -0x7ff90000);
        // UNREACHABLE
    }
    int16_t * v4 = SysAllocString((int16_t *)lpWideCharStr); // 0x10003257
    if (cchWideChar >= 0x1000) {
        // 0x10003267
        free(lpWideCharStr);
    }
    if (v4 != NULL) {
        // 0x10003280
        __writefsdword(0, v1);
        return _40___security_check_cookie_40_4();
    }
    // 0x10003274
    function_100030f0(-0x7ff8fff2);
    // UNREACHABLE
}

// Address range: 0x100032b0 - 0x100032e5
int32_t function_100032b0(int32_t a1) {
    // 0x100032b0
    int32_t result; // 0x100032b0
    *(int32_t *)result = (int32_t)&g7;
    *(int32_t *)(result + 4) = *(int32_t *)(a1 + 4);
    *(int32_t *)(result + 8) = *(int32_t *)(a1 + 8);
    *(int32_t *)(result + 12) = 0;
    return result;
}

// Address range: 0x100032f0 - 0x10003316
int32_t function_100032f0(void) {
    // 0x100032f0
    int32_t v1; // 0x100032f0
    int32_t v2 = *(int32_t *)(v1 + 8); // 0x100032f3
    *(int32_t *)v1 = (int32_t)&g7;
    int32_t hMem; // bp-4, 0x100032f0
    int32_t * v3 = &hMem; // 0x100032fe
    if (v2 != 0) {
        int32_t v4 = v2; // bp-8, 0x10003302
        v3 = &v4;
    }
    int32_t v5 = *(int32_t *)(v1 + 12); // 0x10003306
    int32_t result = 0; // 0x1000330c
    if (v5 != 0) {
        // 0x1000330e
        *v3 = v5;
        result = (int32_t)LocalFree((int32_t *)hMem);
    }
    // 0x10003315
    return result;
}

// Address range: 0x10003320 - 0x1000335f
int32_t function_10003320(char a1) {
    // 0x10003320
    int32_t result; // 0x10003320
    int32_t v1 = *(int32_t *)(result + 8); // 0x10003326
    *(int32_t *)result = (int32_t)&g7;
    int32_t hMem; // bp-8, 0x10003320
    int32_t * v2 = &hMem; // 0x10003331
    if (v1 != 0) {
        int32_t v3 = v1; // bp-12, 0x10003335
        v2 = &v3;
    }
    int32_t v4 = (int32_t)v2;
    int32_t v5 = *(int32_t *)(result + 12); // 0x10003339
    int32_t v6 = v4; // 0x1000333e
    if (v5 != 0) {
        // 0x10003340
        v6 = v4 - 4;
        *(int32_t *)v6 = v5;
        LocalFree((int32_t *)hMem);
    }
    if ((a1 & 1) != 0) {
        // 0x1000334d
        *(int32_t *)(v6 - 4) = 16;
        _3f__3f_3_40_YAXPAXI_40_Z(&g45, (int32_t)&g45);
    }
    // 0x10003358
    return result;
}

// Address range: 0x10003360 - 0x1000338e
int32_t function_10003360(int32_t a1, int32_t a2, int32_t a3) {
    int32_t v1 = &g7; // bp-20, 0x1000337b
    _CxxThrowException(&v1, &g15);
    // UNREACHABLE
}

// Address range: 0x10003390 - 0x10003396
int32_t function_10003390(void) {
    // 0x10003390
    return _purecall();
}

// Address range: 0x10003396 - 0x1000339c
int32_t function_10003396(void) {
    // 0x10003396
    return __telemetry_main_invoke_trigger();
}

// Address range: 0x1000339c - 0x100033a2
int32_t function_1000339c(void) {
    // 0x1000339c
    return __telemetry_main_return_trigger();
}

// Address range: 0x100033a2 - 0x100033a8
int32_t ___std_exception_copy(void) {
    // 0x100033a2
    return __std_exception_copy();
}

// Address range: 0x100033a8 - 0x100033ae
int32_t ___std_exception_destroy(void) {
    // 0x100033a8
    return __std_exception_destroy();
}

// Address range: 0x100033ae - 0x100033b4
void __CxxThrowException_40_8(int32_t * pExceptionObject, int32_t * pThrowInfo) {
    // 0x100033ae
    _CxxThrowException(pExceptionObject, pThrowInfo);
}

// Address range: 0x100033b4 - 0x100033ba
int32_t function_100033b4(int32_t * a1) {
    // 0x100033b4
    return __std_type_info_destroy_list(a1);
}

// Address range: 0x100033ba - 0x100033c0
int32_t * _memset(int32_t * s, int32_t c, int32_t n) {
    // 0x100033ba
    return memset(s, c, n);
}

// Address range: 0x100033c0 - 0x100033c6
int32_t __except_handler4_common(void) {
    // 0x100033c0
    return _except_handler4_common();
}

// Address range: 0x100033c6 - 0x100033cc
int32_t ___CxxFrameHandler3(void) {
    // 0x100033c6
    return __CxxFrameHandler3();
}

// Address range: 0x100033cc - 0x100033d2
int32_t __callnewh(int32_t Size) {
    // 0x100033cc
    return _callnewh(Size);
}

// Address range: 0x100033d2 - 0x100033d8
int32_t * _malloc(int32_t size) {
    // 0x100033d2
    return malloc(size);
}

// Address range: 0x100033d8 - 0x100033de
void __initterm(void (**First)(), void (**Last)()) {
    // 0x100033d8
    _initterm(First, Last);
}

// Address range: 0x100033de - 0x100033e4
int32_t __initterm_e(int32_t (**First)(), int32_t (**Last)()) {
    // 0x100033de
    return _initterm_e(First, Last);
}

// Address range: 0x100033e4 - 0x100033ea
void function_100033e4(int32_t * ptr) {
    // 0x100033e4
    free(ptr);
}

// Address range: 0x100033ea - 0x100033f0
int32_t __seh_filter_dll(int32_t ExceptionNum, struct _EXCEPTION_POINTERS * ExceptionPtr) {
    // 0x100033ea
    return _seh_filter_dll(ExceptionNum, ExceptionPtr);
}

// Address range: 0x100033f0 - 0x100033f6
int32_t function_100033f0(void) {
    // 0x100033f0
    return _initialize_narrow_environment();
}

// Address range: 0x100033f6 - 0x100033fc
int32_t __initialize_onexit_table(struct _onexit_table_t * Table) {
    // 0x100033f6
    return _initialize_onexit_table(Table);
}

// Address range: 0x100033fc - 0x10003402
int32_t __register_onexit_function(struct _onexit_table_t * Table, int32_t (*Function)()) {
    // 0x100033fc
    return _register_onexit_function(Table, Function);
}

// Address range: 0x10003402 - 0x10003408
int32_t __execute_onexit_table(struct _onexit_table_t * Table) {
    // 0x10003402
    return _execute_onexit_table(Table);
}

// Address range: 0x10003408 - 0x1000340e
int32_t __crt_atexit(void) {
    // 0x10003408
    return _crt_atexit();
}

// Address range: 0x1000340e - 0x10003414
void __cexit(void) {
    // 0x1000340e
    _cexit();
}

// Address range: 0x10003414 - 0x1000341a
bool _IsProcessorFeaturePresent_40_4(int32_t ProcessorFeature) {
    // 0x10003414
    return IsProcessorFeaturePresent(ProcessorFeature);
}

// Address range: 0x10003436 - 0x1000344c
int32_t function_10003436(void) {
    // 0x10003436
    return __chkstk();
}

// Address range: 0x1000347d - 0x10003480
int32_t ___acrt_initialize(void) {
    // 0x1000347d
    int32_t v1; // 0x1000347d
    return v1 & -256 | 1;
}

// Address range: 0x10003480 - 0x10003483
int32_t __is_c_termination_complete(void) {
    // 0x10003480
    return 0;
}

// Address range: 0x10003484 - 0x1000348a
int32_t function_10003484(int32_t * s1, int32_t * s2, int32_t n) {
    // 0x10003484
    return memcmp(s1, s2, n);
}

// Address range: 0x10003490 - 0x1000349f
int32_t function_10003490(void) {
    // 0x10003490
    int32_t v1; // 0x10003490
    int32_t v2 = *(int32_t *)(v1 - 32); // 0x10003492
    _3f__3f_3_40_YAXPAXI_40_Z((int32_t *)v2, (int32_t)&g45);
    return &g45;
}

// Address range: 0x100034c0 - 0x100034cf
int32_t function_100034c0(void) {
    // 0x100034c0
    int32_t v1; // 0x100034c0
    int32_t v2 = *(int32_t *)(v1 - 20); // 0x100034c2
    _3f__3f_3_40_YAXPAXI_40_Z((int32_t *)v2, (int32_t)&g45);
    return &g45;
}

// Address range: 0x100034f0 - 0x100034f8
int32_t function_100034f0(void) {
    // 0x100034f0
    return function_10001530();
}

// Address range: 0x10003540 - 0x1000354c
int32_t function_10003540(int32_t * pvarg) {
    // 0x10003540
    return VariantClear(&g18);
}

// --------------- Statically Linked Functions ----------------

// int32_t ??_G__non_rtti_object@std@@UAEPAXI@Z(int32_t a1);
// int32_t _3f__3f_0_3f__24_basic_ios_40_DU_3f__24_char_traits_40_D_40_std_40__40__40_std_40__40_IAE_40_XZ(void);
// int32_t _3f__3f_1_3f__24__Mpunct_40_D_40_std_40__40_MAE_40_XZ(void);
// int32_t _3f__3f_2_40_YAPAXI_40_Z(int32_t a1);
// int32_t _3f__3f__G__non_rtti_object_40_std_40__40_UAEPAXI_40_Z(int32_t a1);
// int32_t _3f__3f__G_Ref_count_base_40_std_40__40_UAEPAXI_40_Z(int32_t a1);
// int32_t _3f__3f__U_40_YAPAXI_40_Z(int32_t a1);
// int32_t _3f_dllmain_crt_dispatch_40__40_YGHQAUHINSTANCE___40__40_KQAX_40_Z(int32_t * a1, int64_t a2, int32_t * a3);
// int32_t _3f_dllmain_raw_40__40_YGHQAUHINSTANCE___40__40_KQAX_40_Z(int32_t * a1, int64_t a2, int32_t * a3);
// int32_t _3f_find_pe_section_40__40_YAPAU_IMAGE_SECTION_HEADER_40__40_QAEI_40_Z(char * a1, int32_t a2);
// int32_t _40___security_check_cookie_40_4(void);
// int32_t ___scrt_initialize_onexit_tables(int32_t a1);
// int32_t ___scrt_release_startup_lock(int32_t a1);
// int32_t __alloca_probe_16(int32_t a1);
// int32_t __chkstk(void);
// int32_t __SEH_epilog4(void);
// int32_t __SEH_prolog4(int32_t * a1, int32_t a2);
// int atexit(void(* func)(void));

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: microsoft linker (14.0)
// Detected functions: 103

